name: code-style

on:
  push:
  pull_request:

jobs:
  VerifyFormatting:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: ./.github/workflows/install-clang-tools.sh

      - name: Run formatting style check
        run: ./.github/workflows/run-clang-format.sh
