name: macos-test

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  MacOsBuild:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: |
        brew install flex
        export PATH=$(brew --prefix flex)/bin:$PREFIX
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        bazel build ...
