name: macos-test

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  MacOsBuild:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: |
        brew install flex libtool
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        export PATH=$(brew --prefix flex)/bin:$PATH
        export LDFLAGS="-L$(brew --prefix flex)/lib"
        export CXXFLAGS="-L$(brew --prefix flex)/include"
        expxort LIBTOOL=glibtool
        bazel build --sandbox_debug ...
