name: macos-test

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  MacOsBuild:
    runs-on: macos-latest
    steps:
    - name: Install deps
      run: |
        brew install flex bison
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        export PATH=$(brew --prefix flex)/bin:$PATH
        export PATH=$(brew --prefix bison)/bin:$PATH
        bazel test --cxxopt=-Wno-range-loop-analysis --test_output=streamed //common/tools:verible-transform-interactive-test
        bazel test --cxxopt=-Wno-range-loop-analysis --test_output=streamed //verilog/tools/syntax/export_json_examples:verible_verilog_syntax_py
